service: serverless-demo-mario

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  stage: ${opt:stage, self:custom.defaultStage}
  timeout: 5
  environment:
    MONGODB_ATLAS_CLUSTER_URI: "mongodb://admin:admin@cluster0-shard-00-00-5vyxo.mongodb.net:27017,cluster0-shard-00-01-5vyxo.mongodb.net:27017,cluster0-shard-00-02-5vyxo.mongodb.net:27017/scores?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin"
custom:
  defaultStage: dev

functions:
  hello:
    handler: handler.hello
  helloHTTP:
    handler: handler.hello
    events: 
      - http:
          method: get
          path: hello
  cliiners:
    handler: cliinersHandler.handler
    events:
      - http:
          method: get
          path: cliiners
  users:
    handler: usersHandler.handler
    events:
      - http:
          method: get
          path: users